version: '3'

services: 
    db:
        image: mysql
        container_name: 'mysqldb'
        command: mysqld --character-set-server=utf8 --collation-server=utf8_general_ci
        restart: always
        ports: 
          - '3306:3306'
        environment:
          MYSQL_ROOT_PASSWORD: 123
          MYSQL_USER: chaor
          MYSQL_PASSWORD: 123
        volumes:
          - /usr/docker/beta/mysql-init:/docker-entrypoint-initdb.d
    web:
        build: .
        container_name: 'aspnetcore'
        ports:
          - '8003:80'
        depends_on:
          - db